# Multi line
config_data: |
  extends: default
  rules:
    document-start:
      present: false
    line-length:
      max: 125
      allow-non-breakable-words: true
      allow-non-breakable-inline-mappings: false
