name: Build Project

on:
  workflow_call:
    inputs:
      themes: # And array of theme name we need to build
        description: 'The theme folder name(s) to build in array format. Example: [linchpin-mmxxii]'
        default: '["none"]'
        required: false
        type: string
      site_url:
        description: 'The site url we are deploying to (full url)'
        required: true
        type: string
      environment:
        description: 'The environment we are deploying to (production, staging, dev)'
        default: 'staging'
        required: false
        type: string
      branch:
        description: 'The branch we are working out of'
        default: 'staging'
        required: false
        type: string
      php_version:
        description: 'PHP version used during build (Default 7.4.x)'
        default: '7.4'
        required: false
        type: string
      node_version:
        description: 'Node version used during build (Default 16.x)'
        default: 14
        required: false
        type: number
    outputs:
      deployment_id:
        description: 'The ID of our deployment'
        value: ${{ jobs.preflight.outputs.deployment_id }}
      workflow_run_id:
        description: 'The ID of the workflow run (used by other shared workflows)'
        value: ${{ jobs.preflight.outputs.run_id }}
      mantle_deploy_id:
        description: 'The ID of the workflow run (used by other shared workflows)'
        value: ${{ jobs.preflight.outputs.mantle_deployment_id }}
    secrets:
      packagist_auth:
        description: 'Authentication for private satis/packagist'
        required: true
      mantle:
        description: 'Secret to deploy to mantle'
        required: false

jobs:
  preflight:
    name: Preflight Setup
    runs-on: ubuntu-latest
    # Map step output to a job output, We have to map to the step "outputs"
    # so we can reference the data in our preflight job as well as outside our preflight job
    outputs:
      branch: ${{ steps.output_data.outputs.branch }}
      deployment_id: ${{ steps.deployment_data.outputs.deployment_id }}
      deployment_post: ${{ steps.deployment_data.outputs.deployment_post }}
      changelog: ${{ steps.changelog_reader.outputs.changes }}
      run_id: ${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Current Version
        id: version
        run: |
          echo ::set-output name=current::${GITHUB_REF#refs/tags/v}

      - name: Get branch name
        id: branch
        uses: tj-actions/branch-names@v5.1

      # Get our changelog if we are a tag and we have a version
      - name: Get Newest Changelog Entry
        if: ${{ steps.branch.outputs.branch.is_tag != 'false' && startsWith( steps.branch.outputs.current_branch, 'v' ) }}
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.version.outputs.current }}
          path: ./CHANGELOG.md

      - name: Escape changelog
        id: changelog
        uses: linchpin/escape-markdown-for-json@v1
        with:
          markdown: ${{ steps.changelog_reader.outputs.changes }}

      - name: Create Mantle Deployment
        uses: linchpin/send-to-mantle@main
        id: send_to_mantle
        with:
          mantle-uri: "${{ inputs.site_url }}/wp-json/mantle/v1/deployment"
          mantle-secret: "${{ secrets.mantle }}"
          mantle-payload: "{\"action\":\"created\",\"deployment\":{\"task\":\"deploy\",\"payload\":{\"version\":\"${{ steps.version.outputs.current }}\",\"committer\":\"${{ github.actor }}\",\"changelog\":\"${{ steps.changelog.outputs.escaped_markdown }}\"}}}"
          soft-fail: true

      - name: Create GitHub Deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repo}/deployments
          repo: ${{ github.repository }}
          ref: ${{ inputs.branch }}
          environment: ${{ inputs.environment }}
          payload: "{\"post_id\":\"${{ fromJson( steps.send_to_mantle.outputs.data ).post_id }}\", \"version\":\"${{ steps.version.outputs.current }}\",\"committer\":\"${{ github.actor }}\",\"changelog\":\"${{ steps.changelog.outputs.escaped_markdown }}\"}"
          mediaType: '{"previews": ["flash", "ant-man"]}'
          required_contexts: '[]'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Deployment Data
        id: deployment_data
        run: |
          echo "::set-output name=mantle_deployment_id::${{ fromJson( steps.send_to_mantle.outputs.data ).post_id }}"
          echo "::set-output name=deployment_id::${{ fromJson( steps.create_deployment.outputs.data ).id }}"

      - name: Set Deployment Status to Pending
        id: start_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repo}/deployments/{deployment}/statuses
          repo: ${{ github.repository }}
          deployment: ${{ steps.deployment_data.outputs.deployment_id }}
          environment: ${{ inputs.environment }}
          environment_url: ${{ inputs.site_url }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          state: pending
          mediaType: '{"previews": ["flash", "ant-man"]}'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  dependency_setup:
    name: Composer
    runs-on: ubuntu-latest
    needs: preflight
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'build'

      - name: Authenticate Packagist
        run: echo '${{ secrets.packagist_auth }}' > $GITHUB_WORKSPACE/build/auth.json

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer Install
        uses: php-actions/composer@v6
        with:
          working_dir: ./build
          dev: no
          php_version: ${{ inputs.php_version }}

      - name: Remove Packagist Authentication
        run: rm -f $GITHUB_WORKSPACE/build/auth.json

      - name: Compress Composer Artifact
        id: composer_compression_artifact
        run: |
          tar -zcf composer.tar.gz ./build

      - name: Upload Dependencies
        uses: actions/upload-artifact@v2
        with:
          path: composer.tar.gz

  # Loop through all of the themes passed from inputs.themes
  theme_setup:
    name: Theme(s)
    runs-on: ubuntu-latest
    needs: preflight
    strategy:
      matrix:
        theme: ${{ fromJSON( inputs.themes ) }}
    steps:
        # check if we have a theme to build. If None output and skip the rest of the steps.
      - name: Theme Setup
        id: individual_theme
        if: ${{ matrix.theme == 'none' }}
        run: |
          echo "::warning::Skipping Theme Build"

      - name: Checkout code
        if: ${{ matrix.theme != 'none' }} # skip this step if no themes are included.
        uses: actions/checkout@v2

      - name: Setup Node.js
        if: ${{ matrix.theme != 'none' }} # skip this step if no themes are included.
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ inputs.node_version }}

      - name: Get yarn cache directory path
        if: ${{ matrix.theme != 'none' }} # skip this step if no themes are included.
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn cache
        if: ${{ matrix.theme != 'none' }} # skip this step if no themes are included.
        uses: actions/cache@v2
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build Theme
        if: ${{ matrix.theme != 'none' }} # skip this step if no themes are included.
        id: build-theme
        run: |
          cd themes/${{ matrix.theme }}
          yarn install # @todo exclude dev libraries (make initial non cached build faster)
          yarn build

      - name: Compress Theme Artifact
        if: ${{ matrix.theme != 'none' }} # skip this step if no themes are included.
        id: compress_theme_artifact
        run: |
          tar -zcf theme-${{ matrix.theme }}.tar.gz --exclude "node_modules" themes/${{ matrix.theme }}

      - name: Upload Theme
        if: ${{ matrix.theme != 'none' }} # skip this step if no themes are included.
        uses: actions/upload-artifact@v2
        with:
          path: theme-${{ matrix.theme }}.tar.gz

  build:
    name: Zip
    runs-on: ubuntu-latest
    needs: [preflight,dependency_setup,theme_setup]
    steps:

      - name: Download All Artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./

      - name: Decompress Composer Artifacts
        id: decompress_composer_artifacts
        run: |
          tar -xzf ./artifact/composer.tar.gz -C ./

      - name: Decompress Theme Artifacts
        if: ${{ inputs.themes != '["none"]' }} # skip this step if no themes are included.
        id: decompress_theme_artifacts
        run: |
          tar -xzf ./artifact/theme-*.tar.gz -C ./build

      - name: Clean Build Files/Folders
        id: clean_build_ff
        run: |
          chmod +x ./build/.deployment/cleanup.sh
          sh ./build/.deployment/cleanup.sh

      # temp_archive comes from the cleanup_build_ff step
      - name: Create Release Zip
        id: compression
        run: |
          mv temp_archive release
          zip -r release.zip release

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release.zip
          retention-days: 1
