name: Build Project v3

on:
  workflow_call:
    inputs:
      skip_cache:
        description: "Skip caching of dependency installs"
        required: false
        default: false
        type: boolean

jobs:
  dependency_setup:
    name: Composer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: "build"

      - name: Authenticate Packagist
        if: ${{ vars.REMOTE_PLUGIN_INSTALL == false }}
        run: echo '${{ secrets.PACKAGIST_COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/build/auth.json

      - name: Cache Composer dependencies
        if: ${{ vars.REMOTE_PLUGIN_INSTALL == false && hashFiles( './build/composer') != '' && inputs.skip_cache == true }}
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer Install
        if: ${{ vars.REMOTE_PLUGIN_INSTALL == false }}
        uses: php-actions/composer@v6
        with:
          working_dir: ./build
          dev: no
          php_version: ${{ vars.PHP_VERSION }}

      - name: Remove Packagist Authentication
        if: ${{ vars.REMOTE_PLUGIN_INSTALL == false }}
        run: rm -f $GITHUB_WORKSPACE/build/auth.json

      - name: Upload Dependencies
        uses: actions/upload-artifact@v4
        with:
          name: composer
          path: |
            ./build
            !./build/**/node_modules
            !./build/auth.json
            !./build/**/.git
            !./build/**/.deployment
          retention-days: 1

  # Loop through all themes passed from inputs.themes
  theme_setup:
    name: Theme(s)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        theme: ${{ fromJSON( vars.THEMES ) }}
    steps:
      # check if we have a theme to build. If None output and skip the rest of the steps.
      - name: Theme Setup
        id: individual_theme
        if: ${{ matrix.theme == 'none' }}
        run: |
          echo "::warning::Skipping Theme Build"

      - name: Checkout code
        if: ${{ matrix.theme != 'none' }} # skip this step if no themes are included.
        uses: actions/checkout@v4

      - name: Install Theme ${{ matrix.theme }} Composer Dependencies
        if: ${{ matrix.theme != 'none' && vars.THEME_USES_COMPOSER == true && hashFiles( format( 'themes/{0}/composer.lock', matrix.theme ) ) != '' }} # skip this step if no themes are included or we don't have a composer file
        id: install-theme-composer
        uses: php-actions/composer@v6
        with:
          working_dir: ./themes/${{ matrix.theme }}
          dev: no
          php_version: ${{ vars.PHP_VERSION }}

      - name: Setup Node.js
        if: ${{ matrix.theme != 'none' }} # skip this step if no themes are included.
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Get npm cache directory
        id: npm-cache-dir
        if: ${{ matrix.theme != 'none' && hashFiles( format( 'themes/{0}/package-lock.json', matrix.theme ) ) != '' }}
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Build Theme with npm
        if: ${{ matrix.theme != 'none' && vars.BUILD_THEME_JS != 'false' && hashFiles(format('themes/{0}/package-lock.json', matrix.theme ) ) != '' }} # skip this step if no themes are included or we tell it to skip
        id: build-theme-npm
        run: |
          cd themes/${{ matrix.theme }}
          npm config set cache $(npm config get cache)
          npm install sass-embedded-linux-x64
          npm install --omit=dev
          npm run build
          rm -rf node_modules

      - name: Upload Theme
        if: ${{ matrix.theme != 'none' }} # skip this step if no themes are included.
        uses: actions/upload-artifact@v4
        with:
          name: theme-${{ matrix.theme }}
          path: themes/${{ matrix.theme }}
          retention-days: 1

  # Loop through all plugins passed from input.plugins
  plugin_setup:
    name: Plugin(s)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin: ${{ fromJSON( vars.PLUGINS ) }}
    steps:
      # check if we have a plugin to build. If None output and skip the rest of the steps.
      - name: Plugin Setup
        id: individual_plugin
        if: ${{ matrix.plugin == 'none' }}
        run: |
          echo "::warning::Skipping Plugin Build"

      - name: Setup Node.js
        if: ${{ matrix.plugin != 'none' }} # skip this step if no plugins are included.
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Get npm cache directory
        id: npm-cache-dir
        if: ${{ matrix.plugin != 'none'  }} # skip this step if no plugins are included.
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Build Plugin with npm
        if: ${{ matrix.plugin != 'none' && hashFiles( format( 'themes/{0}/package-lock.json', matrix.plugin ) ) != '' }} # skip this step if no plugins are included.
        id: build-plugin-npm
        run: |
          cd plugins/${{ matrix.plugin }}
          npm config set cache $(npm config get cache)
          npm install --omit=dev
          npm run build --production
          rm -rf node_modules # remove node modules after the build

      - name: Install Plugin Composer Dependencies
        if: ${{ matrix.plugin != 'none' && inputs.plugin_uses_composer == true && hashFiles(format('themes/{0}/composer.lock', matrix.plugin ) ) != '' }} # skip this step if no themes are included or we don't have a composer file
        id: install-plugin-composer
        uses: php-actions/composer@v6
        with:
          working_dir: ./plugins/${{ matrix.plugin }}
          dev: no
          php_version: ${{ vars.PHP_VERSION }}

      - name: Upload Plugin
        if: ${{ matrix.plugin != 'none' }} # skip this step if no themes are included.
        uses: actions/upload-artifact@v4
        with:
          name: plugin-${{ matrix.plugin }}
          path: plugin/${{ matrix.plugin }}
          retention-days: 1

  build:
    name: Zip
    runs-on: ubuntu-latest
    needs: [dependency_setup, theme_setup, plugin_setup]
    steps:
      - name: Download All Artifacts
        id: artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifact
          merge-multiple: true

      - name: Clean Build Files/Folders
        id: clean_build_ff
        run: |
          mkdir -p ./build/.deployment/
          cd ./build/.deployment/
          wget -O cleanup.sh https://raw.githubusercontent.com/linchpin/actions/v3/.deployment/cleanup.sh
          chmod +x ./cleanup.sh
          sh ./cleanup.sh ${{ vars.REMOTE_PLUGIN_INSTALL }}
          cd ../../
          rm -rf ./build/.deployment/

      # temp_archive comes from the cleanup_build_ff step
      - name: Create Release Zip
        id: compression
        run: |
          mv temp_archive release

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release
          retention-days: 1
