name: Continue Deploy to ${{ vars.HOST }} ${{ vars.ENVIRONMENT }}

on:
  workflow_dispatch:
    inputs:
      deployment_id:
        description: 'The deployment ID from previous jobs'
        required: true
        type: string
      workflow_run_id:
        description: 'Workflow Run ID to get artifacts from'
        required: true
        type: string
      deployment_path:
        description: 'Provide if the deployment path is non standard'
        required: false
        default: '/tmp/releases'
        type: string
      environment:
        description: 'The environment to deploy to'
        default: 'staging'
        type: string
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Continue Deploy to ${{ vars.HOST }} ${{ vars.ENVIRONMENT }}
        id: continue_deploy
        uses: ./.github/workflows/deploy-pressable-continue.yml # continue the deployment process
        with:
          deployment_id: ${{ inputs.deployment_id }}
          deployment_path: ${{ inputs.deployment_path }}
          workflow_run_id: ${{ inputs.workflow_run_id }}
          environment: ${{ inputs.environment }}


