name: Deploy to Pressable

on:
  workflow_call:
    inputs:
      deployment_id:
        description: "The deployment ID from the ancestor workflow"
        required: true
        type: string
      workflow_run_id:
        description: "Workflow Run ID to get artifacts from"
        required: true
        type: string
      do_backup:
        description: "Backup the current site before deploying"
        required: false
        default: false
        type: boolean
      deployment_path:
        description: "Provide if the deployment path is non standard"
        required: false
        default: "/tmp/releases"
        type: string
      environment:
        description: "The environment to deploy to"
        required: false
        default: "staging"
        type: string

jobs:
  deploy:
    name: To Pressable
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Current Version
        id: version
        run: echo "current=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Authenticate Pressable API
        id: authenticate
        run: |
          response=$(curl --location --request POST 'https://my.pressable.com/auth/token' \
          --form 'grant_type="client_credentials"' \
          --form 'client_id="${{ secrets.PRESSABLE_API_CLIENT_ID }}"' \
          --form 'client_secret="${{ secrets.PRESSABLE_API_CLIENT_SECRET }}"')
          access_token=$(echo $response | jq -r '.access_token')
          echo "access_token=$access_token" >> $GITHUB_OUTPUT

      - name: Do Backup
        if: ${{ inputs.do_backup == true && steps.authenticate.outputs.access_token }}
        run: |
          curl --location --request GET 'https://my.pressable.com/v1/sites/${{ vars.SITE_ID }}/ondemand-backups' \
          --header 'Authorization: Bearer ${{ github.env.ACCESS_TOKEN }}' \
          --header 'Content-Type: application/json' \

      - name: Deployment In Queue
        id: in_queue_deployment
        if: ${{ inputs.do_backup == 'true' }} # if we are not doing a backup, continue the deployment
        uses: octokit/request-action@v2
        with:
          route: POST /repos/{repo}/deployments/{deployment}/statuses
          repo: ${{ github.repository }}
          deployment: ${{ inputs.deployment_id }}
          environment: ${{ vars.ENVIRONMENT }}
          environment_url: ${{ vars.SITE_URL }}
          log_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          state: queued
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Save Deployment Details
        id: save_deployment
        if: ${{ inputs.do_backup == true }} # if we are not doing a backup, continue the deployment
        run: |
          curl --location --request POST 'https://mantle.linchpin.com/api/v1/deployments/start' \
          --header 'Content-Type: application/json' \
          --header "Authorization: Bearer ${{ secrets.MANTLE_API_BEARER }}" \
          --data-raw '{
            "pressable_site_id": "${{ vars.SITE_ID }}",
            "site_url": "${{ vars.SITE_URL }}",
            "environment": "${{ vars.ENVIRONMENT }}",
            "branch": "${{ steps.branch.outputs.branch }}",
            "deployment_id": ${{ inputs.deployment_id }},
            "workflow_run_id": ${{ inputs.workflow_run_id }},
            "repository": "${{ github.repository }}"
          }'

      - name: Deployment In Progress
        id: in_progress_deployment
        if: ${{ inputs.do_backup != true }} # if we are not doing a backup, continue the deployment
        uses: octokit/request-action@v2
        with:
          route: POST /repos/{repo}/deployments/{deployment}/statuses
          repo: ${{ github.repository }}
          deployment: ${{ inputs.deployment_id }}
          environment: ${{ vars.ENVIRONMENT }}
          environment_url: ${{ vars.SITE_URL }}
          log_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          state: in_progress
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Continue Deploy to Pressable
        id: continue_deploy
        if: ${{ inputs.do_backup != true }} # if we are not doing a backup, continue the deployment
        uses: ./.github/workflows/deploy-pressable-continue.yml # continue the deployment process
        with:
          site_id: ${{ vars.SITE_ID }}
          site_url: ${{ vars.SITE_URL }}
          environment: ${{ vars.ENVIRONMENT }}
          branch: ${{ steps.branch.outputs.branch }}
          deployment_id: ${{ inputs.deployment_id }}
          deployment_path: ${{ inputs.deployment_path }}
          workflow_run_id: ${{ inputs.workflow_run_id }}
          remote_plugin_install: ${{ inputs.remote_plugin_install }}
