name: Deploy to WP Engine

on:
  workflow_call:
    inputs:
      site_id:
        description: 'The ID of the install on Pressable we are deploying to'
        required: true
        type: number
      site_url:
        description: 'The site url we are deploying to (full url)'
        required: true
        type: string
      environment:
        description: 'The environment we are deploying to (production, staging, dev)'
        required: false
        default: 'staging'
        type: string
      branch:
        description: 'The branch we are deploying to'
        required: false
        default: 'staging'
        type: string
      deployment:
        description: 'The deployment ID from previous jobs'
        required: true
        type: string
      deployment_path:
        description: 'Provide if the deployment path is non standard'
        required: false
        default: '/tmp/releases'
        type: string
      workflow_run_id:
        description: 'Workflow Run ID to get artifacts from'
        required: true
        type: string
      remote_plugin_install:
        description: 'Remotely install plugins instead of using composer'
        required: false
        default: false
        type: boolean
      do_backup:
        description: 'Backup the current site before deploying'
        required: false
        default: false
        type: boolean
    secrets:
      deployment_ssh_key:
        description: 'Pressable SSH Key needed for deployment'
        required: true
      deployment_ssh_user:
        description:  'Username associated with the deployment'
        required: true
      deployment_ssh_host:
        description: 'The SSH host name on pressable we are deploying to, different than hostname of site'
        required: true
      gh_bot_token:
        description: 'Bot Access to Private repo'
        required: true

jobs:
  deploy:
    name: To Pressable
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.site_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Current Version
        id: version
        run: echo "current=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Get branch name
        id: branch
        uses: tj-actions/branch-names@v7
          
      - name: Authenticate Pressable API
        if: ${{ always() && 'production' == inputs.environment }}
        run: |
            response=$(curl --location --request POST 'https://my.pressable.com/auth/token' \
            --form 'grant_type="client_credentials"' \
            --form 'client_id="${{ secrets.pressable_api_client_id }}"' \
            --form 'client_secret="${{ secrets.pressable_api_client_secret }}"')
            access_token=$(echo $response | jq -r '.access_token')
            echo "access_token=$access_token" >> $GITHUB_OUTPUT

      - name: Do Backup
        if: ${{ inputs.do_backup == true }}
        run: |
          curl --location --request GET 'https://my.pressable.com/v1/sites/${{ secrets.site_id }}/ondemand-backups' \
          --header 'Authorization: Bearer ${{ env.access_token }}' \
          --header 'Content-Type: application/json' \

      - name: Enable Maintenance Mode
        run: |
          curl --location --request PUT 'https://my.pressable.com/v1/sites/${{ secrets.site_id }}/maintenance-mode' \
          --header 'Authorization: Bearer ${{ env.access_token }}' \
              
      - name: Deployment In Progress
        id: in_progress_deployment
        uses: octokit/request-action@v2
        with:
          route: POST /repos/{repo}/deployments/{deployment}/statuses
          repo: ${{ github.repository }}
          deployment: ${{ inputs.deployment }}
          environment: ${{ inputs.environment }}
          environment_url: ${{ inputs.site_url }}
          log_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          state: in_progress
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        id: download
        with:
          name: 'release'
          path: ./

      - name: Generate release zip
        id: folder
        run: |
          echo "folder=$(date +'%s')" >> $GITHUB_OUTPUT  

      - name: Configure SSH Connection with WP Engine
        uses: linchpin/actions-pressable-ssh@main
        with:
          ssh_user: ${{ secrets.deployment_ssh_user }}
          ssh_key: ${{ secrets.deployment_ssh_key }}
          ssh_host: ${{ secrets.deployment_ssh_host }}

      - name: Upload Assets
        id: upload_assets
        run: |
          mv ./release.zip ./${{ steps.folder.outputs.folder }}.zip
          ssh pressable "mkdir -p ${{ inputs.deployment_path }}/"
          rsync -e "ssh -p 22" -W --progress "${{ steps.folder.outputs.folder }}.zip" wpengine:~/sites/"${{ inputs.install_name }}"/"${{ inputs.deployment_path }}"

      - name: Put site into Maintenance Mode
        id: maintenance_mode
        run: |
          

      - name: Execute Commands On Server
        id: execute_bash
        run: |
          ssh wpengine "cd ~/sites/${{ inputs.install_name }}/${{ inputs.deployment_path }}/ && wget -O ./entrypoint.sh https://raw.githubusercontent.com/linchpin/actions/v2/.deployment/wpengine-entrypoint.sh && chmod +x ./entrypoint.sh && bash ./entrypoint.sh ${{ steps.folder.outputs.folder }}"


  # Loop through all themes passed from inputs.themes
  plugin_install:
    name: WordPress Plugin Install(s)
    runs-on: ubuntu-latest
    needs: deploy
    steps:

      # When installing the plugins we only need the lock file
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'build'
          sparse-checkout: |
            composer.lock
          sparse-checkout-cone-mode: false

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Configure SSH Connection with WP Engine
        uses: linchpin/actions-wpengine-ssh@main
        with:
          ssh_user: ${{ inputs.install_name }}
          ssh_key: ${{ secrets.deployment_ssh_key }}
          ssh_host: "${{ inputs.install_name }}.ssh.wpengine.net"

      - name: Remote Plugin Install
        if: ${{ inputs.remote_plugin_install != false }}
        id: parse_composer_lock
        shell: bash
        run: |
          wget -O remote-plugin-install.sh https://raw.githubusercontent.com/linchpin/actions/v2/.deployment/remote-plugin-install.sh
          chmod +x ./remote-plugin-install.sh
          bash ./remote-plugin-install.sh ${{ inputs.install_name }} ${{ secrets.SATISPRESS_USER }} ${{ secrets.SATISPRESS_PASSWORD }}


  status:
    name: Deploy Status
    runs-on: ubuntu-latest
    needs: [ deploy, plugin_install ]
    steps:
      - name: Configure SSH Connection with Pressable
        uses: linchpin/actions-pressable-ssh@main
        with:
          ssh_user: ${{ secrets.deployment_ssh_user }}
          ssh_key: ${{ secrets.deployment_ssh_key }}
          ssh_host: "${{ secrets.deployment_ssh_host }}

      - name: Cleanup Maintenance
        id: cleanup_maintenance
        run: |
          ssh pressable "cd ${{ inputs.deployment_path }}/release/.deployment/ && wget -O endpoint.sh https://raw.githubusercontent.com/linchpin/actions/v3/.deployment/pressable-endpoint.sh && chmod +x ./endpoint.sh && bash ./endpoint.sh"

      - name: Set Deployment Status as Successful
        if: ${{ success() }}
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repo}/deployments/{deployment}/statuses
          repo: ${{ github.repository }}
          deployment: ${{ inputs.deployment }}
          environment: ${{ inputs.environment }}
          environment_url: ${{ inputs.site_url }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          state: success
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Set Deployment Status as Failboat
        if: ${{ failure() }}
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repo}/deployments/{deployment}/statuses
          repo: ${{ github.repository }}
          deployment: ${{ inputs.deployment }}
          environment: ${{ inputs.environment }}
          environment_url: ${{ inputs.site_url }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          state: failure
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
