name: WordPress Autofixer

on:
  workflow_call:

jobs:
  phpcbf-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ vars.PHP_VERSION }}
          coverage: none
          tools: cs2pr, composer

      - name: Authenticate packagist.linchpin.com
        run: echo '${{ secrets.PACKAGIST_COMPOSER_AUTH_JSON }}' > ./auth.json

      - name: Create a new branch
        run: |
          git config --global user.name 'Linchpin Bot'
          git config --global user.email 'dev@linchpin.com'
          git checkout -b ${{ github.ref_name }}-phpcbf

      - name: Install Composer dependencies
        run: |
          composer update
          rm -f ./auth.json

      # Check the code-style consistency of the PHP files.
      - name: Fix PHP code style
        id: codestyle
        continue-on-error: true
        run: ${{ github.workspace }}/vendor/squizlabs/php_codesniffer/bin/phpcbf . --standard=${{ github.workspace }}/phpcs.xml > phpcbf-report.txt

      - name: Commit changes
        run: |
          git add .
          git commit -m "ci(NO-TASK): PHPCBF Auto Fix"

      - name: Push changes
        run: git push origin ${{ github.ref_name }}-phpcbf

      - name: Read PHPCBF report
        id: read_report
        run: |
          REPORT=$(cat phpcbf-report.txt)
          echo "report<<EOF" >> $GITHUB_ENV
          echo "$REPORT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          commit-message: PHPCBF Auto Fix
          committer: Linchpin Bot <dev@linchpin.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{ github.ref_name }}-phpcbf
          delete-branch: true
          title: 'Auto Fix Formatting'
          body: |
            **PHPCBF Report:**
            ```
            ${{ env.REPORT }}
            ```
          labels: |
            phpcs
            automated pr
          milestone: 1
          draft: false
