name: WordPress Coding Standards Inspections

on:
  workflow_call:
    secrets:
      token:
        description: "GitHub Token"

jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run PHPCS inspection
        uses: rtCamp/action-phpcs-code-review@v3
        env:
          GH_BOT_TOKEN: ${{ secrets.token }}
