name: WordPress Coding Standards Inspections

on:
  workflow_call:
    secrets:
      bot_token:
        description: 'Github Bot Token'
        required: true

jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run PHPCS inspection
        uses: rtCamp/action-phpcs-code-review@v3.0.1
        env:
          GH_BOT_TOKEN: ${{ secrets.bot_token }}
