name: WordPress Coding Standards Inspections

on:
  workflow_call:

jobs:
  phpcs_code_review:
    if: github.ref != 'refs/heads/release-please--branches--main'
    timeout-minutes: 5
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run PHPCS inspection
        uses: rtCamp/action-phpcs-code-review@v3
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          PHPCS_PHP_VERSION: ${{ vars.PHP_VERSION }}
