name: PHP Lint

on:
  workflow_call:
    inputs:
      php_version:
        description: "The PHP version to lint against"
        required: false
        default: "8.2"
        type: string

jobs:
  phplint_project:
    name: Lint Project
    if: github.ref != 'refs/heads/release-please--branches--main'
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Check commit message for "#skip-lint"
        id: check_commit_message
        if: "!contains(github.event.head_commit.message , 'skip-lint')"
        run: |
            echo "skip_lint=true" >> $GITHUB_OUTPUT

      - name: Authenticate packagist.linchpin.com
        run: echo '${{ secrets.PACKAGIST_COMPOSER_AUTH_JSON }}' > ./auth.json

      - name: Cache Composer Dependencies
        if: ${{ steps.check_commit_message.outputs.skip_lint != 'true' && hashFiles( './composer.lock') != '' }}
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer Install
        uses: php-actions/composer@v6
        if: ${{ steps.check_commit_message.outputs.skip_lint != 'true' }}
        with:
          working_dir: ./
          php_version: ${{ inputs.php_version }}

      - name: Cleanup Auth
        run: |
          rm ./auth.json

      - name: PHP Lint 8.3
        if: ${{ inputs.php_version == '8.3' && steps.check_commit_message.outputs.skip_lint != 'true' }}
        uses: overtrue/phplint@main
        with:
          path: ./

      - name: PHP Lint 8.2
        if: ${{ inputs.php_version == '8.2' && steps.check_commit_message.outputs.skip_lint != 'true' }}
        uses: overtrue/phplint@9.5
        with:
          path: ./

      - name: PHP Lint 8.1
        if: ${{ inputs.php_version == '8.1' && steps.check_commit_message.outputs.skip_lint != 'true' }}
        uses: overtrue/phplint@9.4
        with:
          path: ./

      - name: PHP Lint 8.0
        if: ${{ inputs.php_version == '8.0' && steps.check_commit_message.outputs.skip_lint != 'true' }}
        uses: overtrue/phplint@9.0
        with:
          path: ./
