name: PHP Lint

on:
  workflow_call:

jobs:
  phpcbf-fixer:
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Check commit message for "#skip-lint"
        id: check_commit_message
        run: |
          commit_message="$(git log --format=%B -n 1 ${{ github.sha }})"
          if [[ $commit_message == *"#skip-lint"* ]]; then
            echo "Commit message contains #skip-lint. Skipping linting..."
            echo "skip_lint=true" >> $GITHUB_OUTPUT
          else
            echo "Commit message does not contain #skip-lint. Running linting..."
            echo "skip_lint=false" >> $GITHUB_OUTPUT
          fi

      - name: Authenticate packagist.linchpin.com
        run: echo '${{ secrets.PACKAGIST_COMPOSER_AUTH_JSON }}' > ./auth.json

      - name: Cache Composer dependencies
        if: steps.check_commit_message.outputs.skip_lint == false && hashFiles( './build/composer.lock') != ''
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer Install
        uses: php-actions/composer@v6
        if: steps.check_commit_message.outputs.skip_lint == false
        with:
          working_dir: ./
          php_version: ${{ vars.PHP_VERSION }}

      - name: Cleanup Auth
        run: |
          rm ./auth.json

      - name: PHP Lint 8.3
        if: ${{ vars.PHP_VERSION == '8.3' && steps.check_commit_message.outputs.skip_lint == false }}
        uses: overtrue/phplint@main
        with:
          path: ./

      - name: PHP Lint 8.2
        if: ${{ vars.PHP_VERSION == '8.2' && steps.check_commit_message.outputs.skip_lint == false }}
        uses: overtrue/phplint@9.5
        with:
          path: ./

      - name: PHP Lint 8.1
        if: ${{ vars.PHP_VERSION == '8.1' && steps.check_commit_message.outputs.skip_lint == false }}
        uses: overtrue/phplint@9.4
        with:
          path: ./

      - name: PHP Lint 8.0
        if: ${{ vars.PHP_VERSION == '8.0' && steps.check_commit_message.outputs.skip_lint == false }}
        uses: overtrue/phplint@9.0
        with:
          path: ./
