name: PHP Lint

on:
  workflow_call:
    inputs:
      php_version:
        description: 'PHP version used during build (Default 8.2)'
        default: '8.2'
        required: false
        type: string
    secrets:
      packagist_auth:
        description: 'Authentication for private satis/packagist'
        required: true

jobs:
  phpcbf-fixer:
    runs-on: ubuntu-latest-lg
    steps:
      - uses: actions/checkout@v4

      - name: Parse commit message
        id: parse_commit_message
        run: echo "message=$(git log --format=%B -n 1 ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Check commit message
        id: check_commit_message
        run: |
          commit_message="${{ steps.parse_commit_message.outputs.message }}"
          if [[ "$commit_message" == *"#skip-lint"* ]]; then
            echo "Commit message contains #skip-lint. Skipping linting..."
            echo "skip_lint=true" >> $GITHUB_OUTPUT
          else
            echo "Commit message does not contain #skip-lint. Running linting..."
            echo "skip_lint=false" >> $GITHUB_OUTPUT
          fi

      - name: Authenticate packagist.linchpin.com
        run: echo '${{ secrets.packagist_auth }}' > ./auth.json
        
      - name: Cache Composer dependencies
        if: ${{ steps.check_commit_message.outputs.skip_lint != 'true' && hashFiles( './build/composer') }}
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer Install
        uses: php-actions/composer@v6
        if: steps.check_commit_message.outputs.skip_lint != 'true'
        with:
          working_dir: ./
          php_version: ${{ inputs.php_version }}

      - name: Cleanup Auth
        run: |
          rm ./auth.json

      - name: PHP Lint 8.0+
        if: steps.check_commit_message.outputs.skip_lint != 'true'
        uses: overtrue/phplint@9.0
        with:
          path: ./

