name: Update README.md

on:
  workflow_call:
    inputs:
      base:
        description: 'Where the branch is based from. Typically release please'
        required: false
        default: 'release-please--branches--main'
        type: string
      branch:
        description: 'What branch do we create when updating the readme'
        required: false
        default: 'release-please--branches--main--readme'
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      # Checkout just the README.md file since that's all we're adjusting
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          sparse-checkout: |
            README.md
            composer.lock
          sparse-checkout-cone-mode: false

      - name: Get Branch Names
        id: branch
        uses: tj-actions/branch-names@v7

      - name: Update README.md with parsed README.md data
        run: |
          wget -O update-readme.sh https://raw.githubusercontent.com/linchpin/actions/v3/.deployment/update-readme.sh
          chmod +x ./update-readme.sh
          sh ./update-readme.sh
        
      - name: Commit changes to README.md
        run: |
          git config --local user.email "linchpin-bot@github.com"
          git config --local user.name "Linchpin Bot"

          git add README.md

          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "skip_pr=true" >> $GITHUB_OUTPUT
            
          else
            git commit -m "Update README.md with plugin list"
            echo "skip_pr=false" >> $GITHUB_OUTPUT
          fi
        id: commit_changes

      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v7
        id: create_pr
        with:
          commit-message: "[automated] Update Plugin List"
          title: "[Maintenance] Update README.md WordPress Plugin List"
          body-path: README.md
          base: 'release-please--branches--main' # Use the same branch for PR updates
          branch: 'release-please--branches--main--readme' # Use the same branch for PR updates
          labels: |
            wordpress
            automated pr
            maintenance
          token: ${{ secrets.GH_BOT_TOKEN }}
  
      - name: Automerge Pull Request
        if: steps.create_pr.outputs.pull-request-number != null
        run: gh pr merge --merge --auto "${{ steps.create_pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
