name: Yaml Lint

on:
  push:
    branch:
      - 'main' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  yaml_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/
          config_file: .ymllint.yml
      - run: echo ${{ steps.lint.outputs.logfile }}
