name: Yaml Lint

on:
  push:
    branches:
      - main
      - develop
      - v3
      - v2


jobs:
  yaml_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: YML Lint
        id: lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/
          config_file: .ymllint.yml
      - run: echo ${{ steps.lint.outputs.logfile }}
